language: java
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - oracle-java8-installer
cache:
  directories:
  - "$HOME/.m2"
install: echo Install phase has been disabled as a complete build is run during deployment
script: mvn package
branches:
  only:
  - master
notifications:
  email:
    recipients:
    - vatbub123+travisbuildnotification@googlemail.com
    on_success: never
on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: q12E9MEXuuj0lA+GLPnpq88/6oby1unD29yuQLsJrlj5lwWWdzmgNtIDxFRjdtjRQFhemcwYMeb4XWS/gwaWBhbJ8GugIybDcptuybLt9LnPEsYh7C6XGLBJP0N6b8Zx9DFMChpr7mLbOhff8Fth2Vxr62AUqNxEtCQDzC6+gNYKgCvhLK50b7zGII60wN0rir21YQxTWaImzF295NLX0hAaisZsAn3T65YTPjqzyrX+sdIN6aETePHywwgx4SGrwKrlnnn9aT52gcyU/9mJuafii/0RK+FrfQiV4bBh6bA5PZwmLviYFy5dtjxDsdGFeJSfjQ+4z55qcDMsy92B7uRsM/DfaZxVq1b4+qhHSc8k18diEIret8XrR+zR1FNEafznBEXfjdQVajTdLiuPV6AUBKJCFGi1SpZHFzcpcBd1K2SKj8UnuoSltginxEvQD7im8S6z84w4h3LJiHxRrA7gKEmJrcfM24+5vVvE5GBGR0DQjOfW6CJoq0JNvGTNTrA/GR43uWBRDDvXB6h8Y/zSy8uL+LYxPq91I79KBFpdxPRuJHECWFlTCL+3VUG63xoWBR1E2JCqeFtMSrY/uG2FyQ54yq1PY9ufMkId8PufIRskHM5PCcSzSYaA+xxWuwoX5OQSF3DOcED2jD3Kuf//5mLR2O4eRw7dCcQIdgo=
  app: hello-world-45536
  on:
    repo: vatbub/warexercise2
